import os

QS_35_STABLE = [
    'Does the sentence describe a personal reflection or thought?',
    'Does the sentence contain a proper noun?',
    'Does the sentence describe a physical action?',
    'Does the sentence describe a personal or social interaction that leads to a change or revelation?',
    'Does the sentence involve the mention of a specific object or item?',
    'Does the sentence involve a description of physical environment or setting?',
    'Does the sentence describe a relationship between people?',
    'Does the sentence mention a specific location?',
    'Is time mentioned in the input?',
    'Is the sentence abstract rather than concrete?',
    "Does the sentence express the narrator's opinion or judgment about an event or character?",
    'Is the input related to a specific industry or profession?',
    'Does the sentence include dialogue?',
    'Does the sentence describe a visual experience or scene?',
    'Does the input involve planning or organizing?',
    'Does the sentence involve spatial reasoning?',
    'Does the sentence involve an expression of personal values or beliefs?',
    'Does the sentence contain a negation?',
    'Does the sentence describe a sensory experience?',
    'Does the sentence include technical or specialized terminology?',
    'Does the input contain a number?',
    'Does the sentence contain a cultural reference?',
    'Does the text describe a mode of communication?',
    'Does the input include a comparison or metaphor?',
    'Does the sentence express a sense of belonging or connection to a place or community?',
    'Does the sentence describe a specific sensation or feeling?',
    'Does the text include a planning or decision-making process?',
    'Does the sentence include a personal anecdote or story?',
    'Does the sentence involve a discussion about personal or social values?',
    'Does the text describe a journey?',
    'Does the input contain a measurement?',
    'Does the sentence describe a physical sensation?',
    'Does the sentence include a direct speech quotation?',
    'Is the sentence reflective, involving self-analysis or introspection?',
    'Does the input describe a specific texture or sensation?',
]

# note: only 54 stable in this setting as 2 qs get dropped from the previous 36
QS_36_56_STABLE = [
    'Is the input about a discovery or realization?',
    'Does the sentence include an account of a miscommunication or misunderstanding?',
    'Does the sentence include a specific sound or auditory description?',
    'Does the sentence use a unique or unusual word?',
    'Does the sentence describe a change in a physical or emotional state?',
    'Does the sentence describe a moment of relief or resolution of tension?',
    'Does the sentence include a conditional clause?',
    'Does the sentence reference a specific time or date?',
    "Is the sentence conveying the narrator's physical movement or action in detail?",
    'Is there mention of a city, country, or geographic feature?',
    'Does the sentence involve an unexpected incident or accident?',
    'Does the sentence involve a recount of a social or community event?',
    'Does the sentence express a philosophical or existential query or observation?',
    'Does the story involve a personal project or creation?',
    'Is the sentence emotionally positive?',
    'Does the sentence describe an activity related to daily life or routine?',
    'Does the text include a reference to a past era or time period?',
    'Does the input discuss a societal issue or social justice topic?',
    'Does the sentence convey a decision or choice made by the narrator?',
    'Does the sentence convey a sense of urgency or haste?',
    'Is the sentence providing an explanation or rationale?',
]

# note: 64 additional QS that werent in the previous (119 were stable bc 2 were dropped form previous 56)
QS_57_121 = [
    'Does the sentence use irony or sarcasm?',
    'Does the input include a description of clothing?',
    'Does the input involve a craft or handiwork project?',
    'Does the input involve a financial topic or economic concept?',
    'Does the sentence include a comparison or simile?',
    'Does the sentence include a threat or warning?',
    'Does the sentence describe a physical sensation (e.g., touch, taste)?',
    'Does the sentence involve a personal anecdote about family or friends?',
    'Is the input expressing a wish or desire?',
    'Is the sentence related to education or learning?',
    'Is the sentence expressing admiration or praise?',
    'Is there a description of a landscape or natural scene?',
    'Is there a discussion of a social issue?',
    'Is there a mention of a scientific fact or concept?',
    'Is there a mention of a puzzle or mystery?',
    'Is the sentence designed to persuade or convince?',
    'Does the input mention a social or community issue?',
    'Does the sentence involve a description of a cultural or societal change?',
    'Is there a mention of a specific food or drink?',
    'Is there a mention of reading or writing?',
    'Is the sentence a command?',
    'Does the sentence use past tense?',
    'Is the sentence conveying a strategic or tactical thought by the narrator?',
    'Is there a mention of a gift or present?',
    'Does the sentence involve a description of a group activity or social gathering?',
    'Does the sentence describe a lesson learned or insight gained by the narrator?',
    'Does the sentence involve moral reasoning?',
    'Does the sentence describe a character in a story?',
    'Does the input describe a moment of realization or epiphany?',
    'Does the sentence involve a discussion or description of a mental health issue?',
    'Does the sentence involve a discussion of a familial relationship?',
    'Does the sentence describe a routine activity?',
    'Is the sentence structured as a list?',
    'Is the sentence related to food or eating?',
    'Does the sentence describe a notable change in a personal or professional context?',
    'Is a specific tool or equipment mentioned?',
    'Is a specific color or pattern described?',
    'Does the sentence include a foreign word or phrase?',
    'Does the sentence reference a specific time of day?',
    'Does the sentence involve a safety or security concern?',
    'Is a personal preference or taste described?',
    'Does the sentence describe an unexpected encounter or meeting?',
    'Does the sentence include a description of a life-altering moment?',
    'Does the story include a lesson or moral?',
    'Does the story include a portrayal of a city or urban setting?',
    'Does the story involve a game or sport?',
    'Does the sentence describe an indoor setting?',
    'Does the sentence describe an interaction with technology?',
    'Does the sentence contain a first-person narrative?',
    'Does the story describe a shopping experience?',
    'Is the sentence in the passive voice?',
    'Is the sentence in the active voice?',
    'Is the sentence intended to be motivational or inspirational?',
    'Does the text describe an act of kindness?',
    'Does the sentence describe an experience of learning or gaining new knowledge?',
    'Does the story mention a health issue or injury?',
    'Does the input discuss a personal achievement or milestone?',
    'Does the input discuss a collaboration or team effort?',
    'Does the input contain advice or recommendations?',
    'Does the sentence mention a past or historical event?',
    'Does the input describe a nighttime setting?',
    'Does the input describe a specific emotion in detail?',
    'Does the sentence involve a recounting of a memorable event or anecdote?'
]

QS_HYPOTHESES = [
    'Does the input mention anything related to food?',
    'Does the input mention or describe a sound?',
    'Does the input mention or describe a visual experience?',
    'Does the input mention or describe a smell?',
    'Does the input mention or describe a texture?',
    'Does the input mention or describe a taste?',
    'Does the input mention a number less than 5?',
    'Does the input mention a number greater than 100?',
    'Does the input mention or describe highly positive emotional valence?',
    'Does the input mention or describe highly negative emotional valence?',
    'Does the input mention or describe high emotional intensity?',

    'Does the input mention anything related to an action?',
    'Does the input mention anything related to arithmetic?',
    'Does the input contain a sense of ambiguity?',
    'Does the input mention anything related to anger?',
    'Does the input mention anything related to arguing?',
    'Does the input mention anything related to calculation?',
    'Does the input mention anything related to color?',
    'Does the input mention anything related to conflict?',
    'Does the input mention anything related to debate?',
    'Does the input mention anything related to disgust?',
    'Does the input mention anything related to empathy?',
    'Does the input mention anything related to exactness?',
    'Does the input mention anything related to faces?',
    'Does the input mention anything related to fashion?',
    'Does the input mention anything related to speed?',
    'Does the input mention anything related to fear?',
    'Does the input mention anything related to sadness?',
    'Does the input mention anything unpleasant?',
    'Does the input mention anything related to hands?',
    'Does the input mention anything related to alcohol?',
    'Does the input mention anything related to age?',
    'Does the input mention anything related to children?',
    'Does the input mention anything related to diseases?',
    'Does the input mention anything related to eyes?',
    'Does the input mention anything related to knowledge?',
    'Does the input mention anything related to gender?',
    'Does the input mention anything related to navigation?',
    'Does the input mention anything related to motor movements?',
]

QS_HYPOTHESES_COMPUTED = [
    'Does the input contain a measurement?',
    'Does the input contain a number?',
    'Does the input contain a sense of ambiguity?',
    'Does the input describe a specific texture or sensation?',
    'Does the input discuss a societal issue or social justice topic?',
    'Does the input include a comparison or metaphor?',
    'Does the input involve planning or organizing?',
    'Does the input mention a number greater than 100?',
    'Does the input mention a number less than 5?',
    'Does the input mention anything related to age?',
    'Does the input mention anything related to an action?',
    'Does the input mention anything related to anger?',
    'Does the input mention anything related to arguing?',
    'Does the input mention anything related to arithmetic?',
    'Does the input mention anything related to calculation?',
    'Does the input mention anything related to children?',
    'Does the input mention anything related to color?',
    'Does the input mention anything related to conflict?',
    'Does the input mention anything related to debate?',
    'Does the input mention anything related to diseases?',
    'Does the input mention anything related to disgust?',
    'Does the input mention anything related to empathy?',
    'Does the input mention anything related to eyes?',
    'Does the input mention anything related to food?',
    'Does the input mention anything related to gender?',
    'Does the input mention anything related to knowledge?',
    'Does the input mention anything related to motor movements?',
    'Does the input mention anything related to navigation?',
    'Does the input mention or describe a smell?',
    'Does the input mention or describe a sound?',
    'Does the input mention or describe a taste?',
    'Does the input mention or describe a texture?',
    'Does the input mention or describe a visual experience?',
    'Does the input mention or describe high emotional intensity?',
    'Does the input mention or describe highly negative emotional valence?',
    'Does the input mention or describe highly positive emotional valence?',
    'Does the sentence contain a cultural reference?',
    'Does the sentence contain a negation?',
    'Does the sentence contain a proper noun?',
    'Does the sentence convey a decision or choice made by the narrator?',
    'Does the sentence convey a sense of urgency or haste?',
    'Does the sentence describe a change in a physical or emotional state?',
    'Does the sentence describe a moment of relief or resolution of tension?',
    'Does the sentence describe a personal or social interaction that leads to a change or revelation?',
    'Does the sentence describe a personal reflection or thought?',
    'Does the sentence describe a physical action?',
    'Does the sentence describe a physical sensation?',
    'Does the sentence describe a relationship between people?',
    'Does the sentence describe a sensory experience?',
    'Does the sentence describe a specific sensation or feeling?',
    'Does the sentence describe a visual experience or scene?',
    'Does the sentence describe an activity related to daily life or routine?',
    'Does the sentence express a philosophical or existential query or observation?',
    'Does the sentence express a sense of belonging or connection to a place or community?',
    "Does the sentence express the narrator's opinion or judgment about an event or character?",
    'Does the sentence include a conditional clause?',
    'Does the sentence include a direct speech quotation?',
    'Does the sentence include a personal anecdote or story?',
    'Does the sentence include a specific sound or auditory description?',
    'Does the sentence include an account of a miscommunication or misunderstanding?',
    'Does the sentence include dialogue?',
    'Does the sentence include technical or specialized terminology?',
    'Does the sentence involve a description of physical environment or setting?',
    'Does the sentence involve a discussion about personal or social values?',
    'Does the sentence involve a recount of a social or community event?',
    'Does the sentence involve an expression of personal values or beliefs?',
    'Does the sentence involve an unexpected incident or accident?',
    'Does the sentence involve spatial reasoning?',
    'Does the sentence involve the mention of a specific object or item?',
    'Does the sentence mention a specific location?',
    'Does the sentence reference a specific time or date?',
    'Does the sentence use a unique or unusual word?',
    'Does the story involve a personal project or creation?',
    'Does the text describe a journey?',
    'Does the text describe a mode of communication?',
    'Does the text include a planning or decision-making process?',
    'Does the text include a reference to a past era or time period?',
    'Is the input about a discovery or realization?',
    'Is the input related to a specific industry or profession?',
    'Is the sentence abstract rather than concrete?',
    "Is the sentence conveying the narrator's physical movement or action in detail?",
    'Is the sentence emotionally positive?',
    'Is the sentence providing an explanation or rationale?',
    'Is the sentence reflective, involving self-analysis or introspection?',
    'Is there mention of a city, country, or geographic feature?',
    'Is time mentioned in the input?',
]

QUESTIONS_GPT4 = QS_35_STABLE + QS_HYPOTHESES + QS_36_56_STABLE
QUESTIONS_GPT4_COMPUTED_FULL = QS_35_STABLE + \
    QS_HYPOTHESES_COMPUTED + QS_36_56_STABLE

if __name__ == '__main__':
    assert len(QS_35_STABLE) == 35
    assert len(QS_36_56_STABLE) == 56-35, len(QS_36_56_STABLE)

    computed_gpt4_qs = [
        x.replace('.pkl', '') for x in os.listdir('/home/chansingh/mntv1/deep-fMRI/qa/cache_gpt')
        if '?' in x
    ]
    for q in computed_gpt4_qs:
        print(repr(q) + ',')

    for q in QS_35_STABLE:
        assert q in computed_gpt4_qs
    for q in QS_35_STABLE:
        assert q in computed_gpt4_qs
    for q in QS_HYPOTHESES_COMPUTED:
        assert q in computed_gpt4_qs
    # for q in QS_HYPOTHESES:
        # assert q in computed_gpt4_qs, 'Missing these hypotheses still'

    print(f'{len(QS_35_STABLE)=} {len(QS_36_56_STABLE)=} {len(QS_57_121)=} {len(QS_HYPOTHESES)=} {len(QS_HYPOTHESES_COMPUTED)=}')
